### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by semion13** [olegJF/olx_home_parser#1]
hi, can u modify the script for olx.ro ? thx.

**Comment by olegJF** [comment]
Hi!
Unfortunately, I don't understand Romanian. But I think, you can do it yourself. You need change base_url for your requirements and it all - the script will work well.
Regards Oleg.

**Comment by semion13** [comment]
Actually i need a script who can export all ads from a category like https://www.olx.ro/hobby-sport-turism/biciclete-fitness/biciclete/ or https://www.olx.ro/hobby-sport-turism/biciclete-fitness/biciclete-copii/ with title, price, phone, description, location, 2-3 images into cvs/xml/json file. can u help me ?

**Comment by olegJF** [comment]
These are two different parsers. The first parser for parsing url-addresses from the main page with a list of goods. Second parser for scraping data (title, price, phone, description, location, 2-3 images) for each url-address from the main page.
I can do it, but unfortunately, I have no time.

**Comment by lerdem** [comment]
@semion13 you can use https://github.com/lerdem/olx-parser. I have checked *.ro domain is compatible with parser.

Also adding preview for rss reader and csv file.

[![r1-rss.png](https://i.postimg.cc/jqyN3M3c/r1-rss.png)](https://postimg.cc/5jN66SVQ)
[![r2-csv.png](https://i.postimg.cc/brqvB9dV/r2-csv.png)](https://postimg.cc/r0YcdW15)

**Comment by olegJF** [comment]
closed
